== Tutorial #01 - Callbacks and mouse

=== Basic application callbacks

One of the first concepts to learn is the life cycle of your application and the associated event callbacks.

Callback functions are automatically called by the framework in particular moments during the life of the game, for example at the beginning of a frame or at shutdown.

Let's write a small example that uses them.

[source,lua]
----
nc = ncine

function nc.on_init()
	texture_ = nc.texture.new(nc.fs.get_data_path().."textures/texture2.png")

	local resolution = nc.application.get_resolution()
	pos_ = {x = resolution.x * 0.5, y = resolution.y * 0.5}
	sprite_ = nc.sprite.new(nc.application.get_rootnode(), texture_, pos_)

	angle_ = 0
end

function nc.on_frame_start()
	angle_ = angle_ + 2 * nc.application.get_interval()

	local radius = nc.application.get_width() * 0.2
	local newpos = {x = pos_.x + radius * math.sin(angle_), y = pos_.y + radius * math.cos(angle_)}
	nc.sprite.set_position(sprite_, newpos)
end

function nc.on_shutdown()
	nc.sprite.delete(sprite_)
	nc.texture.delete(texture_)
end
----

The first line is just a way to create a shorter alias for the `ncine` table: the API access point.

==== on_init() and on_shutdown()

The `on_init()`function is called only once, at the beginning of your application. Here we are creating a new texture and a new sprite using the special `new()` function.

The `on_shutdown()` function is its mirror, it is called before the application quits and should be used to free any resources created for the game: there is one `delete()` for each `new()` we called earlier.

All functions that work on objects created with a `new()` need those objects as their first parameter, and `delete()` is no exception.

To create a texture object we just need the filename of an image file. You can use an absolute path but in this example we are using the `data/` directory by asking the filesystem table `fs` for the default data path.

Next we create a sprite object by passing four parameters to the `sprite.new()` function: a parent node, a texture object, and the X and Y coordinates of the initial position.

As a parent node we use the root node of the scenegraph by calling the `get_rootnode()` function of the `application` table. Every sprite that you want to display on screen needs to be a child of this node or to have an ancestor that is a child of this node.

The other function from the `application` table, `get_resolution`, returns the resolution of the screen and it is used here to place the sprite at the center of the screen.

==== on_frame_start()

The `on_frame_start()` function is where most of the game logic happens, it is called once at the beginning of each frame and allows you to update objects, like move sprite arounds, play sounds, and so on.

In this example we move the sprite in a circle path by using some simple trigonometry and the Lua math library.

We increment the `angle_` variable and use it to update the sprite position with the `sprite.set_position()` function. By using the interval time passed since last frame we keep a stable rotation regardless of the frame time oscillations.

==== on_pre_init()

We can make the example a bit more flexible by configuring some aspects before our application or the framework even initialize.

For this we can use the `on_pre_init()` callback. It receives a configuration table that we can modify before returning it.

[source,lua]
----
function nc.on_pre_init(cfg)
	cfg.resolution = {x = 1280, y = 720}
	cfg.window_title = "nCine example"
	return cfg
end
----

There are many more variables in this table, but for this example we are just setting the initial window resolution and title.

=== Mouse input

==== on_mouse_button_released()

Even if we a have a moving sprite on screen, this example is still boring: we cannot interact with it.

Let's remedy to this by adding the ability to move the sprite around with the mouse.

[source,lua]
----
function nc.on_mouse_button_released(event)
	if event.button == nc.mouse_button.LEFT then
		pos_ = {x = event.x, y = event.y}
	end
end
----

The `on_mouse_button_released()` function is called every time the user releases a mouse button. It receives an event table with additional information, like which button was released.

We are performing this check by comparing the `button` variable with the `mouse_button.LEFT` constant value. Those special constant values are usually written with capital letters.

If the user released the left button, we update the `pos_` variable that will be used as the center of the rotation animation in the `on_frame_start()` function.

The coordinates of the mouse at the time a button was released are accessible in the `x` and `y` variables of the same table.

==== on_mouse_moved()

You will soon discover that smashing the mouse button is not an optimal way for continuously updating the sprite position. For this you need a different function.

The `on_mouse_moved()` function is called every time the mouse is moved and receives a state table that you can query in a way similar to the event one of `on_mouse_button_released()`.

[source,lua]
----
function nc.on_mouse_moved(state)
	if state.left_pressed then
		pos_ = {x = state.x, y = state.y}
	end
end
----

In this snippet we first check if we are moving the mouse while pressing the left mouse button by checking the value of the `left_pressed` boolean variable, then we use the `x` and `y` variables to update the position.

=== Putting it all together

.Complete example #01
[source,lua]
----
include::src/script_01.lua[]
----
